const vouchers = [
    {
        id: "1",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "2",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "3",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "4",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    {
        id: "5",
        createdAt: "",
        updatedAt: "",
        code: "",
        link: "",
        status: "",
    },
    
];

export default vouchers;
