import "./globals.scss";
import type { Metadata } from "next";
import React, { ReactNode } from "react";
import Aos from "@/components/Aos";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: ReactNode;
};

const RootLayout = function ({ children }: Readonly<Props>) {
    return (
        <html lang="en">
            <Aos />
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
